version: '3.9'

services:

  api:
    build: .
    container_name: pokemon-api

    ports:
      - "8000:8000"

    environment:
      - MONGO_URI=mongodb://mongo:27017/pokemondb
      - PORT=8000

    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: pokemon-mongo

    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: